<a href="https://colab.research.google.com/github/akanshadevrani/Indian_Population_Analysis/blob/main/IndianPopulationAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv('/content/Table_2A_State_Uts.csv')

In [4]:
data.head()

,Category,India/State/Union Territory,Population 2011,Decadal Population Growth Rate - 2001-2011,Population Density (per sq.km) - 2011
0,India,India,1210854977,17.7,368
1,State,Andhra Pradesh,49386799,9.0,308
2,State,Arunachal Pradesh,1383727,26.0,17
3,State,Assam,31205576,17.1,398
4,State,Bihar,104099452,25.4,1106

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 5 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Category                                    37 non-null     object
 1   India/State/Union Territory                 37 non-null     object
 2   Population 2011                             37 non-null     int64
 3   Decadal Population Growth Rate - 2001-2011  37 non-null     float64
 4   Population Density (per sq.km) - 2011       37 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.6+ KB

In [6]:
data.columns

Index(['Category', 'India/State/Union Territory', 'Population 2011',
       'Decadal Population Growth Rate - 2001-2011',
       'Population Density (per sq.km) - 2011'],
      dtype='object')

In [7]:
data=data.rename(columns={'India/State/Union Territory':'State','Population 2011':'Population', 'Decadal Population Growth Rate - 2001-2011':'Growth Rate','Population Density (per sq.km) - 2011':'Density'})

In [8]:
data.head()

  Category              State  Population  Growth Rate  Density
0    India              India  1210854977         17.7      368
1    State     Andhra Pradesh    49386799          9.0      308
2    State  Arunachal Pradesh     1383727         26.0       17
3    State              Assam    31205576         17.1      398
4    State              Bihar   104099452         25.4     1106

In [9]:
data=data[data['State']!='India']

In [10]:
data=data.drop_duplicates()

In [12]:
data.isnull().sum()

Category       0
State          0
Population     0
Growth Rate    0
Density        0
dtype: int64

In [15]:
data['Growth Rate']=data['Growth Rate'].astype(str).str.replace('%','')
data['Growth Rate']=pd.to_numeric(data['Growth Rate'])
data['Population']=pd.to_numeric(data['Population'])
data['Density']=pd.to_numeric(data['Density'])

In [16]:
data.head()

  Category              State  Population  Growth Rate  Density
1    State     Andhra Pradesh    49386799          9.0      308
2    State  Arunachal Pradesh     1383727         26.0       17
3    State              Assam    31205576         17.1      398
4    State              Bihar   104099452         25.4     1106
5    State       Chhattisgarh    25545198         22.6      189

In [17]:
data.describe()

         Population  Growth Rate       Density
count  3.600000e+01    36.000000     36.000000
mean   3.363486e+07    19.280556   1074.222222
std    4.305205e+07    11.226647   2359.164575
min    6.447300e+04    -0.600000     17.000000
25%    1.439840e+06    13.750000    174.750000
50%    2.106970e+07    18.000000    334.500000
75%    5.215002e+07    22.825000    732.250000
max    1.998123e+08    55.900000  11320.000000

In [18]:
data.to_excel('Cleaned_population_dataset.xlsx',index=False)

In [19]:
from google.colab import files
files.download('Cleaned_population_dataset.xlsx')